{% set name = "blueqat" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/blueqat-{{ version }}.tar.gz
  sha256: 6d70938269001d0d155f6a9f200d735778eafc808f8192b78dd72078f2e461e5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.19
    - python >=3.6
    - scipy >=1.5

test:
  imports:
    - blueqat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Blueqat/Blueqat
  summary: Quantum Computer Library for Everyone
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
