{% set name = "blueqat" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/blueqat-{{ version }}.tar.gz
  sha256: 397fe0c7aacfc457ae1e64d09de35971de3c3d137ccd668e7d2d8d4563a906ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy =1.21.0
    - python >=3.6
    - scipy >=1.5
    - autoray
    - matplotlib
    - networkx
    - opt-einsum >=3.3.0
    - quimb

test:
  imports:
    - blueqat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Blueqat/Blueqat
  summary: Quantum Computer Library for Everyone
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
