{% set name = "blueqat" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/blueqat-{{ version }}.tar.gz
  sha256: a3aa40736977b823ff482bd0a3998929f4383791cc528586252c6b8677142d89

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - numpy >=1.19
    - python >=3.6
    - scipy >=1.5

test:
  imports:
    - blueqat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Blueqat/Blueqat
  summary: Quantum Computer Library for Everyone
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
